"""atualizando modelo vaccination

Revision ID: 20653066fc08
Revises: 341fbf2b1f5f
Create Date: 2022-02-22 10:25:59.417820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20653066fc08'
down_revision = '341fbf2b1f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccine_cards', 'health_unit_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccine_cards', 'health_unit_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
