"""atualizando nullable

Revision ID: 341fbf2b1f5f
Revises: 5e0deb37e553
Create Date: 2022-02-22 09:47:57.949109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '341fbf2b1f5f'
down_revision = '5e0deb37e553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccine_cards', 'first_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vaccine_cards', 'second_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vaccine_cards', 'health_unit_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccine_cards', 'health_unit_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vaccine_cards', 'second_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vaccine_cards', 'first_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
